#!/bin/bash

cd ${0%/*}

port=5927
branch=test
repo="git@bitbucket.org:amutake/andon-articles.git"

function andon_shutdown() {
    if [ -f RUNNING_PID ]; then
        cat RUNNING_PID | xargs kill
        echo "kill process"
    else
        echo "already killed"
    fi
}

function andon_startup() {
    play "start -Dhttp.port=${port}"
}

function andon_restart() {
    play compile

    andon_shutdown
    andon_startup
}

function andon_backup() {

    if [ -f ./db/h2.jar ]; then
        now=`date +%Y-%m-%d`

        echo 'git push history...'
        cd history
        git remote add origin $repo || true
        git tag -a ${branch}-${now} -m 'automatically backup'
        git push origin ${branch}-${now}
        cd ../
        echo 'done.'

        echo 'compressing files...'
        tar czf backup/${now}.tar.gz ./files
        echo 'done.'

        echo 'dumping sql...'
        cd db
        ./backup.sh
        mv backup.sql ../backup/${now}.sql
        echo 'done.'
        cd ../

        echo "Success!"
    else
        echo "h2.jar not found. abort."
    fi
}

function andon_restore() {

    if [ -f ./backup/${1}.tar.gz ] && [ -f ./backup/${1}.sql ] && [ -f ./db/h2.jar ]; then
        echo "${1}.tar.gz and ${1}.sql found"
        printf "[caution!] "
        printf "This command will delete current contents and restore to specified version. "
        printf "OK? [Y/n]: "
        read ok
        if [ "$ok" == "Y" ] || [ "$ok" == "y" ]; then

            echo "play compile..."
            play compile
            echo "done."

            echo "Restore application to version-${1}!"

            andon_shutdown

            echo 'restoring history...'
            cd history
            git fetch --tags
            git checkout ${branch}-${1}
            cd ../
            echo 'done.'

            echo "restoring files..."
            rm -r files
            tar xzf backup/${1}.tar.gz
            echo "done."

            echo 'restoring db...'
            cd db
            rm default.*
            ./restore.sh ../backup/${1}
            echo 'done.'
            cd ../

            andon_startup
        else
            echo "abort."
        fi
    else
        echo "not found: backup/${1}.tar.gz or backup/${1}.sql or db/h2.jar"
        echo "please make sure if exists"
    fi
}

case "$1" in
    start)
        andon_startup
        ;;
    stop)
        andon_shutdown
        ;;
    restart)
        andon_restart
        ;;
    backup)
        andon_backup
        ;;
    restore)
        andon_restore $2
        ;;
    *)
        echo "Usage: andon (start|stop|restart|backup|restore)"
esac
